"""Reusable image extraction, description, and music generation helpers."""

from .image_describer import (
    ImageDescription,
    ImagePart,
    describe_image,
    extract_features,
    extract_image_parts,
    load_image,
    save_parts,
)
from .eleven_labs import (
    ElevenLabsMusicResult,
    build_elevenlabs_prompt,
    generate_elevenlabs_music,
    save_elevenlabs_music_result,
)
from .midi_selector import (
    MidiCandidate,
    MidiSelection,
    choose_midi_for_image,
    choose_midi_from_description,
    list_midi_files,
    load_midi_manifest,
)
from .midi_arranger import (
    FullArrangementResult,
    HarmonicAnalysis,
    LayerPalette,
    MidiArrangementResult,
    Section,
    VibeProfile,
    analyse_chord_midi,
    create_chord_drum_arrangement,
    create_full_arrangement,
    default_arrangement_path,
    palette_for,
    plan_sections,
    vibe_from_features,
)
from .soundfont_picker import (
    SoundFontEntry,
    SoundFontSelection,
    load_soundfont_manifest,
    pick_soundfont,
    vibe_bucket,
)
from .ambient_model import (
    AmbientChord,
    AmbientMusicState,
    ModalKey,
    active_layers,
    ambient_state_for,
    chord_change_seconds,
    chord_for_time,
    generate_chord_progression,
    modal_scale_pitches,
    pick_modal_key,
    smooth_vibe,
    tempo_from_vibe,
    vibe_from_feature_dict,
)
from .pyo_ambient_engine import (
    PyoAmbientEngine,
    PyoEngineStatus,
)
from .sounddevice_ambient_engine import (
    SoundDeviceAmbientEngine,
    SoundDeviceEngineStatus,
)

__all__ = [
    "AmbientChord",
    "AmbientMusicState",
    "ElevenLabsMusicResult",
    "FullArrangementResult",
    "HarmonicAnalysis",
    "ImageDescription",
    "ImagePart",
    "LayerPalette",
    "MidiArrangementResult",
    "MidiCandidate",
    "MidiSelection",
    "ModalKey",
    "PyoAmbientEngine",
    "PyoEngineStatus",
    "Section",
    "SoundDeviceAmbientEngine",
    "SoundDeviceEngineStatus",
    "SoundFontEntry",
    "SoundFontSelection",
    "VibeProfile",
    "active_layers",
    "analyse_chord_midi",
    "ambient_state_for",
    "build_elevenlabs_prompt",
    "chord_change_seconds",
    "chord_for_time",
    "choose_midi_for_image",
    "choose_midi_from_description",
    "create_chord_drum_arrangement",
    "create_full_arrangement",
    "default_arrangement_path",
    "describe_image",
    "extract_features",
    "extract_image_parts",
    "generate_chord_progression",
    "generate_elevenlabs_music",
    "list_midi_files",
    "load_midi_manifest",
    "load_image",
    "load_soundfont_manifest",
    "modal_scale_pitches",
    "palette_for",
    "pick_soundfont",
    "pick_modal_key",
    "plan_sections",
    "save_elevenlabs_music_result",
    "save_parts",
    "smooth_vibe",
    "tempo_from_vibe",
    "vibe_bucket",
    "vibe_from_features",
    "vibe_from_feature_dict",
]
